### ISSUE TITLE
Estimating Round-off Error Accumulated Over a Loop

### ISSUE THREAD

**Issue by jon-whit** [soarlab/FPTaylor#1]
I am experimenting with FPTaylor by trying to estimate the round-off error that accumulates over a loop. Consider the (Matlab) loop below:

```
x = single(0); % Initialize x to a single precision floating-point variable with value 0.
for i=1:10000
     x = x + 0.0001; % After 10,000 iteration, x should theoretically be equal to x = 1.
end

x % Display x, which shows that x = 1.0001
```

To generate the FPTaylor definitions I unrolled this loop.

```
Variables
    float32 x in [1.0, 2.0]
;
    
Definitions
    defx0 = x + 0.1,
    defx1 = defx0 + 0.1,
    defx2 = defx1 + 0.1,
    defx3 = defx2 + 0.1,
    defx4 = defx3 + 0.1,
    ...
    defx9999 = defx9998 + 0.1
;

Expressions
    defx9999
;
```

FPTaylor hangs on *"Corresponding original subexpressions"*.

Has FPTaylor been tested on expressions as large as this?

**Comment by monadius** [comment]
FPTaylor does not work well with large expressions. I recommend to decrease the number of iterations in your example. Your example is quite simple so FPTaylor can handle about 100 iterations.

Also, you need to add rounding operations:

```
defx0 rnd32= x + 0.1,
defx1 rnd32= defx0 + 0.1,
...
defx99 rnd32= defx98 + 0.1;
```

**Comment by jon-whit** [comment]
Ok.. Your simplified example does not in any way model the same problems as the one I proposed though. If you sum over 100 iterations the expression x + 0.01, you don't get the floating-point error propagation the same as you do when summing the expression x + 0.0001 10,000 times.

It turns out that my example posted previously leads to 1.001, whereas the summation of x + 0.01 100 times leads to the expected value of 1.0.

**Comment by monadius** [comment]
Here is a simple C program which demonstrate that 100 iterations are enough to see an inaccurate final value:

```
#include <stdio.h>

int main()
{
  float x = 0;

  for (int i = 0; i < 100; i++) {
    x = x + 0.01;
  }

  printf("x = %.15f (%a)\n", x, x);

  return 0;
}
```

The final printed value is `x = 0.999999344348907 (0x1.ffffeap-1)`.

If we change the type of x to `double` then we get `x = 1.000000000000001 (0x1.0000000000003p+0)`.

**Comment by jon-whit** [comment]
Ok, sorry for my misunderstanding. I'm working in Matlab, and don't have that same issue.
