### ISSUE TITLE
FPTaylor build failing on Ubuntu 17.10

### ISSUE THREAD

**Issue by keram88** [soarlab/FPTaylor#12]
This is a bug report filed against FPTuner:
https://github.com/soarlab/FPTuner/issues/2

I have tried compiling FPTaylor on Ubuntu 17.10 using the provided OCaml, and OCaml versions 4.00 to 4.05 provided with opam.

The problem appears to be related to building linking non-pic objects:
/usr/bin/ld: chcw.o: relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC

The main fptaylor target is also unable to build (after removing INTERVAL's ocamlfpu target) with a similar error.

**Comment by monadius** [comment]
FPTaylor cannot be also compiled on Ubuntu 16.10. It is a known issue. One should build FPTaylor with `make fptaylor-simple-interval`. At some point, the INTERVAL library should be completely removed. I don't know if there is any good OCaml binding to existing C/C++ interval libraries.

**Comment by monadius** [comment]
Everything should work now with the updated version of the interval library.
