### ISSUE TITLE
urgent！！！A question about the Rigorous Estimation of Floating-Point Round-Off Errors with Symbolic Taylor Expansions paper！！！

### ISSUE THREAD

**Issue by zuoyanzhang** [soarlab/FPTaylor#31]
![image](https://user-images.githubusercontent.com/93237592/186175856-0b5eabb5-4106-437d-b290-280b1c10fe21.png)
The four expressions marked in the red box in the picture are all expressions with functions. I don’t know how s3fp measures the error with function expressions. I would like to ask how s3fp operates to obtain expressions with functions. formula error? Thank you very much if you can answer my question

**Comment by monadius** [comment]
s3fp is neither sound nor complete. It tries to find a good lower bound for the floating-point error but it does not guarantee that the returned value is indeed a lower bound. It is always possible to check that the returned result is a lower bound by evaluating the function at the point returned by s3fp using high precision interval arithmetic (e.g., using the MPFI library).

The results in the table were obtained by comparing two copies of the same function: one computed with the standard double precision arithmetic and another computed with quad-precision arithmetic (as implemented in the GCC quad-precision math library `<quadmath.h>`). `<quadmath.h>` supports all standard transcendental functions (`logq`, `expq`, `sinq`, etc.). s3fp returns inputs for which the difference between the double-precision function and the quad-precision function is as large as possible using a heuristic optimization algorithm.
